MeusLembretes.com/Models/Lembrete.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MeusLembretes.com.Models
{
    [Table("tbl_lembrete")]
    public class Lembrete
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int LembreteId { get; set; }

        public int UsuarioId { get; set; }

        [Required(ErrorMessage ="Um Titulo E Requerido")]
        [MaxLength(50,ErrorMessage ="Maximo de {1} Caracteres Atingido")]
        public string Titulo { get; set; }

        [Required(ErrorMessage = "Uma Mensagem E Requerida")]
        [MaxLength(250, ErrorMessage = "Maximo de {1} Caracteres Atingido")]
        public string Mensagem  { get; set; }

        [Required(ErrorMessage = "Uma Data E Requerida")]
        [DataType(DataType.Date,ErrorMessage ="Formato Invalido")]
        public DateTime RealizacaoData { get; set; }

        [DataType(DataType.Date, ErrorMessage = "Formato Invalido")]
        public DateTime DataCadastro { get; set; }

        [DataType(DataType.Date, ErrorMessage = "Formato Invalido")]
        public DateTime Modificacao { get; set; }

        public virtual Usuario Usuario { get; set; }

    }
}

MeusLembretes.com/Controllers/LembretesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MeusLembretes.com.Models;

namespace MeusLembretes.com.Controllers
{
    public class LembretesController : Controller
    {
        private LembreteContext db = new LembreteContext();

        // GET: Lembretes
        public ActionResult Index()
        {
            var lembretes = db.Lembretes.Include(l => l.Usuario);
            return View(lembretes.OrderBy(l => l.RealizacaoData));
        }

        // GET: Lembretes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lembrete lembrete = db.Lembretes.Find(id);
            if (lembrete == null)
            {
                return HttpNotFound();
            }
            return View(lembrete);
        }

        // GET: Lembretes/Create
        public ActionResult Create()
        {
            ViewBag.UsuarioId = new SelectList(db.Usuarios, "UsuarioId", "UsuarioNome");
            return View();
        }

        // POST: Lembretes/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "LembreteId,UsuarioId,Titulo,Mensagem,RealizacaoData,DataCadastro,Modificacao")] Lembrete lembrete)
        {
            if (ModelState.IsValid)
            {
                lembrete.DataCadastro = DateTime.Now;
                lembrete.Modificacao = DateTime.Now;
                db.Lembretes.Add(lembrete);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UsuarioId = new SelectList(db.Usuarios, "UsuarioId", "UsuarioNome", lembrete.UsuarioId);
            return View(lembrete);
        }

        // GET: Lembretes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lembrete lembrete = db.Lembretes.Find(id);
            if (lembrete == null)
            {
                return HttpNotFound();
            }
            ViewBag.UsuarioId = new SelectList(db.Usuarios, "UsuarioId", "UsuarioNome", lembrete.UsuarioId);
            return View(lembrete);
        }

        // POST: Lembretes/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "LembreteId,UsuarioId,Titulo,Mensagem,RealizacaoData,DataCadastro,Modificacao")] Lembrete lembrete)
        {
            if (ModelState.IsValid)
            {
                lembrete.Modificacao = DateTime.Now;
                db.Entry(lembrete).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UsuarioId = new SelectList(db.Usuarios, "UsuarioId", "UsuarioNome", lembrete.UsuarioId);
            return View(lembrete);
        }

        // GET: Lembretes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lembrete lembrete = db.Lembretes.Find(id);
            if (lembrete == null)
            {
                return HttpNotFound();
            }
            return View(lembrete);
        }

        // POST: Lembretes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Lembrete lembrete = db.Lembretes.Find(id);
            db.Lembretes.Remove(lembrete);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MeusLembretes.com/Views/Lembretes/Create.cshtml
@model MeusLembretes.com.Models.Lembrete

@{
    ViewBag.Title = "Create";
    { Layout = null; }
}
@*<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">*@
<link rel="stylesheet" href="~/Content/bootstrap.min.css">
<link rel="stylesheet" href="~/Content/formulario.css">

<body id="centralcontent">
    <div class="form-container">
        @using (Html.BeginForm("Create", "Lembretes"))
        {
            @Html.AntiForgeryToken()

            <div class="page-header">
                <h1>Novo Lembrete</h1>
            </div>
            <div class="panel panel-success">
                <div class="panel-heading">
                    <h4>Dados do Lembrete</h4>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="form-group col-md-5">
                            @Html.Label("Titulo do Lembrete", htmlAttributes: new { @class = "label-control" })
                            @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control", placeholder = "Escreva aqui o Titulo" } })
                            @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-8">
                            @Html.Label("Mensagem", htmlAttributes: new { @class = "label-control" })
                            @Html.TextAreaFor(model => model.Mensagem, htmlAttributes: new { @class = "form-control", style = "height:250px", placeholder = "Escreva aqui sua Mensagem" })
                            @Html.ValidationMessageFor(model => model.Mensagem, "", new { @class = "text-danger" })

                        </div>
                        <div class="form-group col-md-2">
                            @Html.Label("Lembrar dia", htmlAttributes: new { @class = "label-control" })
                            @Html.EditorFor(m => m.RealizacaoData)
                            @Html.ValidationMessageFor(model => model.RealizacaoData, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group col-md-4">
                            @Html.Label("Usuario", htmlAttributes: new { @class = "label-control" })
                            @Html.DropDownList("UsuarioId", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.UsuarioId, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="panel-footer">
                    <input type="submit" value="Criar" class="btn btn-success">
                    @Html.ActionLink("Voltar", "Index", new { }, new { @class = "btn btn-primary" })
                </div>
            </div>
        }
    </div>
</body>
@*<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>*@

@section Scripts {
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

}

MeusLembretes.com/Views/Lembretes/Delete.cshtml
@model MeusLembretes.com.Models.Lembrete

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Lembrete</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Usuarioy.UsuarioNome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Usuarioy.UsuarioNome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mensagem)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mensagem)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RealizacaoData)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RealizacaoData)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataCadastro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataCadastro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Modificacao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Modificacao)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MeusLembretes.com/Views/Lembretes/Details.cshtml
@model MeusLembretes.com.Models.Lembrete

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Lembrete</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Usuarioy.UsuarioNome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Usuarioy.UsuarioNome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mensagem)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mensagem)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RealizacaoData)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RealizacaoData)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataCadastro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataCadastro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Modificacao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Modificacao)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.LembreteId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MeusLembretes.com/Views/Lembretes/Edit.cshtml
@model MeusLembretes.com.Models.Lembrete

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Lembrete</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.LembreteId)

        <div class="form-group">
            @Html.LabelFor(model => model.UsuarioId, "UsuarioId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UsuarioId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UsuarioId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mensagem, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mensagem, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mensagem, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RealizacaoData, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RealizacaoData, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RealizacaoData, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataCadastro, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataCadastro, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataCadastro, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Modificacao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Modificacao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Modificacao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MeusLembretes.com/Views/Lembretes/Index.cshtml
@model IEnumerable<MeusLembretes.com.Models.Lembrete>

@{
    ViewBag.Title = "Index";
    { Layout = null; }
}

    @*<link rel="stylesheet" href="~/Content/bootstrap.min.css">*@
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<h2 class="text-center">Listagem Lembretes</h2>
<div class="container">
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-md-3">
                <div class="card">
                    <h5 class="card-header">@Html.DisplayFor(mo =>item.Titulo)</h5>
                    <div class="card-body">
                        <p class="card-text">@Html.DisplayFor(mo => item.Mensagem)</p>
                        <a href="#" class="btn btn-primary btn-xs">Editar</a>
                        <a href="#" class="btn btn-warning">Copiar</a>
                    </div>
                    <div class="card-footer">
                        <p>P/dia @Html.DisplayFor(mo => item.RealizacaoData)</p>
                    </div>
                </div>
            </div>
            <br />
        }
    </div>
    <br />
    <div>
        @Html.ActionLink("Voltar", "Index","Home",new { }, new { @class="btn btn-info"})
    </div>
</div>



<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>